Reorder postinst

diff --git a/debian/pt-os-mods.postinst b/debian/pt-os-mods.postinst
--- a/debian/pt-os-mods.postinst
+++ b/debian/pt-os-mods.postinst
@@ -6,17 +6,16 @@ case "${1}" in
 
     # If upgrading from pre-'6.0.0' running on pi-topOS, send desktop notification to run update again
     if dpkg --compare-versions "$2" lt "${min_version_w_apt_key}" && [[ -f "/etc/pt-issue" ]]; then
+      display=":$(find /tmp/.X11-unix/ -maxdepth 1 ! -name .X11-unix |
+        sed 's#/tmp/.X11-unix/X##' | head -n 1)"
+
+      if [[ -z "${display}" ]]; then
+        echo "Unable to find a display"
+        exit 1
+      fi
+
       (
         trap '' HUP EXIT INT TERM QUIT
-
-        display=":$(find /tmp/.X11-unix/ -maxdepth 1 ! -name .X11-unix |
-          sed 's#/tmp/.X11-unix/X##' | head -n 1)"
-
-        if [[ -z "${display}" ]]; then
-          echo "Unable to find a display"
-          exit 1
-        fi
-
         while systemctl is-active --quiet pt-os-updater; do
           sleep 1
         done
@@ -24,7 +23,6 @@ case "${1}" in
         env DISPLAY="${display}" /usr/lib/pt-os-updater/check-now
 
       ) </dev/null &>/dev/null &
-      disown
 
     fi
     ;;
