Add support for new alsa configuration of RPi audio devices
`pt-os-mods` now includes a generic systemd service which can be appropriated for any use case that might require multiple runs or are to be run contextually (as opposed to running at the moment of package installation via `postinst`).

New kernel (>5) has changed how audio appears in Alsa. This commit aims to ensure that audio experience for users is seamless (within reason).

Further changes are likely required for peripherals to continue to work - this will be handled in the device manager and common library as appropriate. 

We have also added tests for `postinst` and for the new systemd service. 🎉

diff --git a/debian/pt-os-mods.postinst b/debian/pt-os-mods.postinst
--- a/debian/pt-os-mods.postinst
+++ b/debian/pt-os-mods.postinst
@@ -1,22 +1,8 @@
 #!/bin/bash -e
 
-case "${1}" in
-configure)
-
-	# Update wpa_supplicant.conf with network credentials
-	if [[ $(grep "Build Number" /etc/pt-issue | awk '{print $NF}') == "C748" ]]; then
-		wireless_interface=$(raspi-config nonint list_wlan_interfaces | head -n 1)
-		if [[ -n $wireless_interface ]]; then
-			echo "Storing wireless interface configuration"
-			wpa_cli -i "${wireless_interface}" save_config >/dev/null 2>&1
-			wpa_cli -i "${wireless_interface}" reconfigure >/dev/null 2>&1
-		fi
-	fi
-
-	dns_file="/etc/resolv.conf.head"
-
-	if [[ ! -f "${dns_file}" ]]; then
-		echo "# [pi-topOS] START
+RESOLV_CONF_HEAD_FILE="/etc/resolv.conf.head"
+apply_cloudflare_dns() {
+	echo "# [pi-topOS] START
 #
 # Set Cloudflare as DNS provider
 #
@@ -25,29 +11,74 @@ nameserver 1.0.0.1
 nameserver 2606:4700:4700::1111
 nameserver 2606:4700:4700::1001
 #
-# [pi-topOS] END" >"${dns_file}"
+# [pi-topOS] END" >"${RESOLV_CONF_HEAD_FILE}"
+}
+
+do_update_check() {
+	local display="${1}"
+	trap '' HUP EXIT INT TERM QUIT
+	while systemctl is-active --quiet pt-os-updater; do
+		sleep 1
+	done
+	env DISPLAY="${display}" /usr/lib/pt-os-updater/check-now
+}
+
+get_display() {
+	local display
+	display="$(pgrep -a Xorg | awk '{print $3}')"
+	[[ -n "${display}" ]] && echo "${display}"
+}
+
+attempt_check_for_updates() {
+	local display
+	display="$(get_display)"
+
+	if [[ -z "${display}" ]]; then
+		echo "Unable to find a display"
+		exit
 	fi
 
-	min_version_w_apt_key="6.0.1"
+	(do_update_check "${display}") &
+}
 
-	# If upgrading from pre-'6.0.1' running on pi-topOS, send desktop notification to run update again
-	if dpkg --compare-versions "$2" lt "${min_version_w_apt_key}" && [[ -f "/etc/pt-issue" ]]; then
-		display="$(pgrep -a Xorg | awk '{print $3}')"
+previous_version_requires_patch() {
+	local version_to_check_against="${1}"
+	# Is new install or version is earlier than upgrade check
+	[[ -z "${previous_version}" ]] || return 0
+	dpkg --compare-versions "${previous_version}" lt "${version_to_check_against}" || return 0
+}
 
-		if [[ -z "${display}" ]]; then
-			echo "Unable to find a display"
-			exit
+is_pi_top_os() {
+	if [[ -f "/etc/pt-issue" ]]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+main() {
+	if is_pi_top_os; then
+		previous_version="${1}"
+
+		# NOTE: some patches are checked on each boot -
+		# 	see 'pt-os-mods' systemd service
+
+		# Apply Cloudflare DNS
+		if previous_version_requires_patch "6.1.0"; then
+			apply_cloudflare_dns
 		fi
 
-		(
-			trap '' HUP EXIT INT TERM QUIT
-			while systemctl is-active --quiet pt-os-updater; do
-				sleep 1
-			done
-			env DISPLAY="${display}" /usr/lib/pt-os-updater/check-now
-		) &
-
+		# Check for updates again (with new apt key)
+		if previous_version_requires_patch "6.0.1"; then
+			attempt_check_for_updates
+		fi
 	fi
+}
+
+case "${1}" in
+configure)
+	shift
+	main "${@}"
 	;;
 
 abort-upgrade | abort-remove | abort-deconfigure) ;;
